language: node_js
os:
  - linux
node_js:
  - "lts/*"
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn install
  - yarn lint
  - yarn type-check
  - yarn md-lint
after_success:
  - if [ "$TRAVIS_BRANCH" = "release" ] && [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then yarn lh -- --perf=90 --pwa=90 --seo=90 --a11y=90 https://blog-staging.rayriffy.com/; fi
